#* 🧙🏻‍♂️BIENVENIDO A LOS PIPELINES DE CONTINUOUS INTEGRATION DE "ARI - Hija de Aurora"!
#? 🤖Este Pipeline de CI se activa al hacer MERGE a la rama "QA" o "MAIN",
#? 🧪Consiste en ejecutar TODOS los tests del Repo e importar los resultados a Jira!🚀
#! 👩🏻‍🔬Este Pipeline de CI NO DEBE EDITARSE sin permiso del QA Lead.
name: 🧪Pipeline Regression in QA
run-name: ${{github.actor}}👨🏻‍🔬 triggered Regression in ${{github.ref_name}}

on:
  push:
    branches:
    - QA

jobs:
  RegressionTesting:
    name: regression
    timeout-minutes: 10 # * Este tiempo es el máximo que puede durar el Pipeline de Regresión.
    runs-on: ubuntu-latest

    steps:

    - name: 📘 Checkout Repo
      uses: actions/checkout@v4

    - name: 💿 Installing Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 🍙 Bun Setup
      uses: oven-sh/setup-bun@v1

    - name: 🧬 Install Project Dependencies
      run: |
        bun install

    - name: 🎭️ Installing Playwright And Browsers
      run: |
        bun run pw:install

    - name: 🎭️ Playwright Regression Test
      run: |
        bun run regression
      env:
        CHATGPT_API_KEY_PW: ${{ secrets.CHATGPT_API_KEY_PW }}
        BASE_URL_QA: ${{ secrets.BASE_URL_QA }}

    - name: 📊Generate Allure Report
      if: always()
      run: |
        bun run allure:gen

    - name: 📡Upload Artifact - Allure Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-playwright-report
        path: allure-report/
        retention-days: 15

    - name: 📡Upload Artifact - Test Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: html-playwright-report
        path: test-html-report/playwright
        retention-days: 15

    - name: ✅Import Test Results to Xray TX
      if: env.XRAY_CLIENT != '' && env.XRAY_SECRET != ''
      uses: mikepenz/xray-action@v3
      with:
        username: ${{ env.XRAY_CLIENT }}
        password: ${{ env.XRAY_SECRET }}
        testFormat: 'junit'
        testPaths: 'test-junit-report/playwright-importer-report.xml'
        testExecKey: 'GX3-2447' #* Este debería ser el TX predeterminado para este Pipeline de Regresión.
        projectKey: 'GX3'
      env:
        XRAY_CLIENT: ${{ secrets.XRAY_CLIENT_ID }}
        XRAY_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}

  Ari-Slack-Notification:
    needs: [RegressionTesting]
    if: always()
    runs-on: ubuntu-latest
    steps:

    - name: 🔔Slack Notification of Done
      if: env.SLACK_WEBHOOK != ''
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Ari✨
        SLACK_MESSAGE: ':test_tube: (PLAYWRIGHT) PROJECT: ChatGPT API Testing: REGRESSION RESULTS IMPORTED TO JIRA :rocket:'
        SLACK_COLOR: ${{ needs.RegressionTesting.result }}
        SLACK_ICON: https://image.cdn2.seaart.ai/2023-12-06/clo9g0h4msbc73ac2sog/99e1abc36f32945cd4bacf5ee7448e96194545f7_high.webp

  Create-PullRequest:
    needs: [RegressionTesting, Ari-Slack-Notification]
    runs-on: ubuntu-latest
    steps:

    - name: 💻Checkout
      uses: actions/checkout@v4

    - name: 🧬 Check for changes (git diff main)
      id: gitDiff
      run: |
        git fetch origin main
        DIFF=$(git diff --name-only origin/main)
        if [ "$DIFF" != "" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: 📦️ Create Pull Request
      if: steps.gitDiff.outputs.changes == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const { repo, owner } = context.repo;
          const result = await github.rest.pulls.create({
          title: '✅[QA REGRESSION PASSED]: Ready to Merge into MAIN',
          owner,
          repo,
          head: '${{ github.ref_name }}',
          base: 'main',
          body: [
              'Update branch by Automation Pipeline:',
              '- (CI) Last Story Test Execution PASSED✅',
              '- (CI) Regression Test Execution PASSED✅',
              '🆗No Conflicts in Repo Source Branch'
          ].join('\n')
          });
          github.rest.issues.addLabels({
          owner,
          repo,
          issue_number: result.data.number,
          labels: ['autoPullRequest']
          });

  AutoMerge-into-Main:
    needs: [Create-PullRequest]
    runs-on: ubuntu-latest
    steps:
    - name: 🧬Merge QA -> MAIN
      uses: devmasx/merge-branch@master
      with:
        type: now
        label_name: 'autoPullRequest'
        target_branch: 'main' #RAMA PRINCIPAL DEL REPOSITORIO PRESENTE
        github_token: ${{ github.token }}
